export type CrmClient = {
	id: string;
	tenant_id: string | null;
	opiekun_id: string | null;
	nazwa: string | null;
	nazwa_skrocona: string | null;
	typ: string | null;
	ulica: string | null;
	nip: string | null;
	regon: string | null;
	krs: string | null;
	pesel: string | null;
	email: string | null;
	telefon: string | null;
	rodo_zgoda: boolean | null;
	rodo_kanal: string | null;
	rodo_data: string | null;
	created_at: string;
	beauty_id: number | null;
	auth_user_id: string | null;
	gwarancje: boolean | null;
};
